"""GROMACS Molecular Dynamics workflow bridge for SharK.

Automates the configuration, parameterization, and launching of nanosecond
GPU-accelerated molecular dynamics simulations from selected docking poses
using the standardized GROMACS md_pipeline.
"""

from __future__ import annotations

from dataclasses import dataclass, field
import os
from pathlib import Path
import shutil
import subprocess
from typing import Optional


def find_gromacs_pipeline(custom_dir: Optional[str | Path] = None) -> Optional[Path]:
    """Locates the GROMACS pipeline root directory dynamically."""
    if custom_dir and Path(custom_dir).is_dir():
        return Path(custom_dir).resolve()

    env_dir = os.environ.get("SHARK_GROMACS_PIPELINE") or os.environ.get("GROMACS_PIPELINE_DIR")
    if env_dir and Path(env_dir).is_dir():
        return Path(env_dir).resolve()

    # Search standard candidate locations
    candidates = [
        Path.home() / "GROMACS" / "md_pipeline",
        Path("/opt/gromacs/md_pipeline"),
        Path.cwd().parent / "GROMACS" / "md_pipeline"
    ]
    for c in candidates:
        if c.is_dir() and (c / "scripts" / "02_prepare_receptor.py").is_file():
            return c.resolve()

    return None


def resolve_gromacs_tool_paths() -> list[Path]:
    """Finds directories containing GROMACS, ACPYPE, and AmberTools binaries."""
    extra_paths: list[Path] = []
    candidates = [
        Path.home() / ".local/share/mamba/envs/gmx_env/bin",
        Path.home() / ".local/share/mamba/envs/gmx_env/bin.AVX2_256",
        Path.home() / "miniforge3/envs/gmx_env/bin",
        Path.home() / "miniconda3/envs/gmx_env/bin",
        Path.home() / "anaconda3/envs/gmx_env/bin",
    ]
    for c in candidates:
        if c.is_dir() and c not in extra_paths:
            extra_paths.append(c)
    return extra_paths


@dataclass
class MDRunResult:
    run_id: str
    run_dir: Path
    sim_time_ns: float
    status: str  # "completed", "failed", "prepared"
    backbone_rmsd_final: Optional[float] = None
    mean_rmsf: Optional[float] = None
    mean_coord_dist: Optional[float] = None
    dashboard_path: Optional[Path] = None


def setup_and_launch_md(
    receptor_pdb: str | Path,
    ligand_pose_file: str | Path,
    ligand_name: str = "LIG",
    ligand_ref_file: Optional[str | Path] = None,
    sim_time_ns: float = 10.0,
    enable_metal_restraint: bool = True,
    run_now: bool = False,
    pipeline_dir: Optional[str | Path] = None,
    work_dir: Optional[str | Path] = None
) -> MDRunResult:
    """Sets up a GROMACS MD run directory and optionally executes the pipeline."""
    pipeline_root = find_gromacs_pipeline(pipeline_dir)
    if pipeline_root is None:
        raise FileNotFoundError(
            "GROMACS pipeline not found. Set SHARK_GROMACS_PIPELINE or GROMACS_PIPELINE_DIR environment variable."
        )

    rec_p = Path(receptor_pdb).resolve()
    lig_p = Path(ligand_pose_file).resolve()

    run_id = f"run_{ligand_name}_{int(sim_time_ns)}ns"
    base_run_dir = Path(work_dir).resolve() if work_dir else (pipeline_root / "runs")
    run_dir = base_run_dir / run_id
    run_dir.mkdir(parents=True, exist_ok=True)
    prep_dir = run_dir / "00_prep"
    prep_dir.mkdir(exist_ok=True)

    # Stage inputs in run prep directory
    shutil.copy2(rec_p, prep_dir / "receptor_raw.pdb")
    shutil.copy2(lig_p, prep_dir / f"{ligand_name}_pose.pdb")

    # Also stage inputs in pipeline_root/inputs for compatibility with 00_extract_pose.sh
    pipe_inputs = pipeline_root / "inputs"
    pipe_inputs.mkdir(parents=True, exist_ok=True)
    shutil.copy2(rec_p, pipe_inputs / f"{run_id}_receptor.pdb")
    shutil.copy2(lig_p, pipe_inputs / f"{run_id}_pose.pdb")

    # Stage reference ligand structure if provided (SDF/MOL/MOL2)
    ref_rel_path = ""
    if ligand_ref_file:
        ref_p = Path(ligand_ref_file).resolve()
        if ref_p.is_file() and ref_p.suffix.lower() in (".sdf", ".mol", ".mol2"):
            ref_ext = ref_p.suffix.lower()
            shutil.copy2(ref_p, prep_dir / f"{ligand_name}_ref{ref_ext}")
            shutil.copy2(ref_p, pipe_inputs / f"{run_id}_ref{ref_ext}")
            ref_rel_path = f"inputs/{run_id}_ref{ref_ext}"

    tool_dirs = [str(p) for p in resolve_gromacs_tool_paths()]
    path_export = f'export PATH="{":".join(tool_dirs)}:$PATH"' if tool_dirs else ""

    # Generate complete config.env honoring Diego's GROMACS pipeline standards
    config_content = f"""# Automatically generated by SharK MD Bridge for GROMACS Pipeline
PROJECT_ROOT="{pipeline_root}"
SCRIPTS_DIR="{pipeline_root}/scripts"
MDP_TEMPLATES_DIR="{pipeline_root}/mdp_templates"

# Environment & PATH resolution for GROMACS / ACPYPE / AmberTools
{path_export}

# Run Identification
RUN_ID="{run_id}"
WORKDIR="{run_dir}"

# Ligand and Receptor Parameters
LIGAND_NAME="{ligand_name}"
LIGAND_RESNAME="{ligand_name[:3].upper()}"
LIGAND_PH="7.4"
LIGAND_CHARGE_METHOD="bcc"
LIGAND_NET_CHARGE="0"
POSRES_FORCE_CONST="1000"
RECEPTOR_NAME="{rec_p.stem}"
CHAIN="ALL"
COFACTORS="HEM,HEME,MUR,CD,CL,FE,GDP,GTP,ADP,ATP,NAD,NADH,NADP,NADPH"
RESTRAINT_FE_N={"true" if enable_metal_restraint else "false"}

# Input Paths (Staged inside {pipeline_root}/inputs and {run_dir}/00_prep)
POLISCREEN_RECEPTOR_PDB="inputs/{run_id}_receptor.pdb"
POLISCREEN_LIGAND_POSE="inputs/{run_id}_pose.pdb"
POLISCREEN_LIGAND_SDF="{ref_rel_path}"

# Force Fields and Solvent Box (Amber / GAFF2 Standard)
PROTEIN_FF="amber99sb-ildn"
WATER_MODEL="spce"
BOX_TYPE="dodecahedron"
BOX_DISTANCE_NM=1.0
SALT_CONCENTRATION_M=0.15

# Thermodynamic and Temporal Parameters
TEMP_K=300.0
PRESSURE_BAR=1.0
DT_PS=0.002
EQ_TIME_PS=100
SIM_TIME_NS={sim_time_ns}

# GPU Acceleration Flags
export CUDA_VISIBLE_DEVICES="${{CUDA_VISIBLE_DEVICES:-GPU-641168ae-17ec-907c-8ac3-e1ac3683f6dc}}"
GPU_FLAGS="-nb gpu -pme gpu -bonded gpu -update gpu"
"""
    cfg_file = run_dir / "config.env"
    cfg_file.write_text(config_content, encoding="utf-8")

    # Update pipeline config/config.env for sub-scripts that source config/config.env directly
    pipe_config_dir = pipeline_root / "config"
    pipe_config_dir.mkdir(parents=True, exist_ok=True)
    (pipe_config_dir / "config.env").write_text(config_content, encoding="utf-8")

    status = "prepared"
    if run_now:
        # Launch pipeline script
        run_script = pipeline_root / "scripts" / "run_pipeline.sh"
        if run_script.is_file():
            print(f"[SharK-MD] Launching simulation {run_id} ({sim_time_ns} ns)...")
            exec_env = os.environ.copy()
            if tool_dirs:
                exec_env["PATH"] = ":".join(tool_dirs) + ":" + exec_env.get("PATH", "")
            res = subprocess.run(
                ["bash", str(run_script), str(cfg_file)],
                cwd=str(run_dir),
                capture_output=True,
                text=True,
                env=exec_env
            )
            log_file = run_dir / "pipeline_exec.log"
            log_content = f"STDOUT:\n{res.stdout}\n\nSTDERR:\n{res.stderr}"
            log_file.write_text(log_content, encoding="utf-8")

            if res.returncode == 0:
                status = "completed"
                print(f"[SharK-MD] Simulation {run_id} completed successfully.")
            else:
                status = "failed"
                print(f"[SharK-MD] Simulation {run_id} failed (exit code {res.returncode}). Log saved to {log_file}")
                err_lines = [l for l in (res.stderr or res.stdout).splitlines() if l.strip()]
                if err_lines:
                    print("[SharK-MD] Error tail:\n" + "\n".join(err_lines[-10:]))

    # Check for analysis outputs
    dash_path = prep_dir / "md_analysis_dashboard.png"
    return MDRunResult(
        run_id=run_id,
        run_dir=run_dir,
        sim_time_ns=sim_time_ns,
        status=status,
        dashboard_path=dash_path if dash_path.is_file() else None
    )


def run_md_from_session(
    session: object,
    ligand_id: str,
    pose_idx: int = 1,
    sim_time_ns: float = 10.0,
    enable_metal_restraint: bool = True,
    run_now: bool = False,
    pipeline_dir: Optional[str | Path] = None,
    work_dir: Optional[str | Path] = None,
    receptor_id: Optional[str] = None
) -> MDRunResult:
    """Extracts raw receptor and pose from PoliScreen session and prepares/launches MD."""
    pose = session.get_pose(ligand_id, pose_idx=pose_idx, receptor_id=receptor_id)
    if pose is None:
        raise ValueError(f"Pose not found in session: ligand={ligand_id}, pose_idx={pose_idx}, receptor={receptor_id}")

    # Retrieve the raw receptor PDB required for pdb2gmx
    raw_receptor_pdb = session.receptor_for(pose.receptor_id, raw=True)
    prep_receptor_pdb = session.receptor_for(pose.receptor_id, raw=False)
    print(f"[SharK-MD] Target Receptor ID: {pose.receptor_id}")
    print(f"[SharK-MD] Staging RAW crystal structure: {raw_receptor_pdb.name} (docking-prepared '{prep_receptor_pdb.name}' bypassed)")
    print(f"[SharK-MD] Classical Force Field: AMBER99SB-ILDN (protein) + GAFF2/AM1-BCC (ligand) + SPC/E (water, 0.15 M NaCl)")

    # Locate reference ligand topology (MOL2 / SDF) if present in session
    ref_lig_path = None
    if hasattr(session, "ligand_files") and session.ligand_files:
        ref_lig_path = session.ligand_files.get(ligand_id.casefold()) or session.ligand_files.get(ligand_id)

    if not ref_lig_path and hasattr(session, "extract_dir") and session.extract_dir:
        for folder in ("input_ligands", "ligandos_entrada", ""):
            cand_dir = session.extract_dir / folder
            if cand_dir.is_dir():
                for f in cand_dir.iterdir():
                    if f.is_file() and f.stem.casefold() == ligand_id.casefold() and f.suffix.lower() in (".mol2", ".sdf", ".mol"):
                        ref_lig_path = f
                        break
            if ref_lig_path:
                break

    if ref_lig_path:
        print(f"[SharK-MD] Matched reference ligand topology: {ref_lig_path.name}")
    else:
        print(f"[SharK-MD] No reference SDF/MOL2 found for {ligand_id}; using OpenBabel pose conversion.")

    return setup_and_launch_md(
        receptor_pdb=raw_receptor_pdb,
        ligand_pose_file=pose.pose_file,
        ligand_name=ligand_id,
        ligand_ref_file=ref_lig_path,
        sim_time_ns=sim_time_ns,
        enable_metal_restraint=enable_metal_restraint,
        run_now=run_now,
        pipeline_dir=pipeline_dir,
        work_dir=work_dir
    )

