"""GROMACS Molecular Dynamics workflow bridge for SharK.

Automates the configuration, parameterization, and launching of nanosecond
GPU-accelerated molecular dynamics simulations from selected docking poses
using the standardized GROMACS md_pipeline.
"""

from __future__ import annotations

from dataclasses import dataclass, field
import os
from pathlib import Path
import shutil
import subprocess
from typing import Optional


def find_gromacs_pipeline() -> Optional[Path]:
    """Locates the GROMACS pipeline root directory dynamically."""
    env_dir = os.environ.get("GROMACS_PIPELINE_DIR")
    if env_dir and Path(env_dir).is_dir():
        return Path(env_dir).resolve()

    # Search standard candidate locations
    candidates = [
        Path.home() / "GROMACS" / "md_pipeline",
        Path("/opt/gromacs/md_pipeline"),
        Path.cwd().parent / "GROMACS" / "md_pipeline"
    ]
    for c in candidates:
        if c.is_dir() and (c / "scripts" / "02_prepare_receptor.py").is_file():
            return c.resolve()

    return None


@dataclass
class MDRunResult:
    run_id: str
    run_dir: Path
    sim_time_ns: float
    status: str  # "completed", "failed", "prepared"
    backbone_rmsd_final: Optional[float] = None
    mean_rmsf: Optional[float] = None
    mean_coord_dist: Optional[float] = None
    dashboard_path: Optional[Path] = None


def setup_and_launch_md(
    receptor_pdb: str | Path,
    ligand_pose_file: str | Path,
    ligand_name: str = "LIG",
    sim_time_ns: float = 10.0,
    enable_metal_restraint: bool = True,
    run_now: bool = False
) -> MDRunResult:
    """Sets up a GROMACS MD run directory and optionally executes the pipeline."""
    pipeline_root = find_gromacs_pipeline()
    if pipeline_root is None:
        raise FileNotFoundError(
            "GROMACS pipeline not found. Set GROMACS_PIPELINE_DIR environment variable."
        )

    rec_p = Path(receptor_pdb).resolve()
    lig_p = Path(ligand_pose_file).resolve()

    run_id = f"run_{ligand_name}_{int(sim_time_ns)}ns"
    run_dir = pipeline_root / "runs" / run_id
    run_dir.mkdir(parents=True, exist_ok=True)
    prep_dir = run_dir / "00_prep"
    prep_dir.mkdir(exist_ok=True)

    # Copy inputs
    shutil.copy2(rec_p, prep_dir / "receptor_raw.pdb")
    shutil.copy2(lig_p, prep_dir / f"{ligand_name}_pose.pdb")

    # Generate custom config.env
    config_content = f"""# Automatically generated by SharK MD Bridge
RUN_ID="{run_id}"
WORKDIR="{run_dir}"
INPUTS_DIR="{pipeline_root}/inputs"
SCRIPTS_DIR="{pipeline_root}/scripts"
TEMPLATES_DIR="{pipeline_root}/mdp_templates"

RECEPTOR_PDB="{prep_dir}/receptor_raw.pdb"
LIGAND_NAME="{ligand_name}"
LIGAND_RESNAME="{ligand_name[:3].upper()}"
LIGAND_SDF="{prep_dir}/{ligand_name}_pose.pdb"
LIGAND_POSE="{prep_dir}/{ligand_name}_pose.pdb"

SIM_TIME_NS={sim_time_ns}
EQ_TIME_PS=100.0
DT_PS=0.002
TEMP_K=300.0
PRESSURE_BAR=1.0

COFACTORS="HEM,HEME,MUR,CD,CL,FE"
RESTRAINT_FE_N={"true" if enable_metal_restraint else "false"}
"""
    cfg_file = run_dir / "config.env"
    cfg_file.write_text(config_content, encoding="utf-8")

    status = "prepared"
    if run_now:
        # Launch pipeline script
        run_script = pipeline_root / "scripts" / "run_pipeline.sh"
        if run_script.is_file():
            print(f"[SharK-MD] Launching simulation {run_id} ({sim_time_ns} ns)...")
            res = subprocess.run(
                ["bash", str(run_script), str(cfg_file)],
                cwd=str(run_dir),
                capture_output=True,
                text=True
            )
            status = "completed" if res.returncode == 0 else "failed"

    # Check for analysis outputs
    dash_path = prep_dir / "md_analysis_dashboard.png"
    return MDRunResult(
        run_id=run_id,
        run_dir=run_dir,
        sim_time_ns=sim_time_ns,
        status=status,
        dashboard_path=dash_path if dash_path.is_file() else None
    )
